### ISSUE TITLE
Combatify Compat Issue

### ISSUE THREAD

**Issue by N-10K** [Truly-Modular/Modular-Item-API#31]
**Describe the Issue**
Combatify is a mod that changes the combat of Minecraft to use the combat in the Combat Test Snapshots, which massively reworks the combat. An issue is that when swinging a modular weapon, the recharge for a charged hit is absurdly slow.

**The other mod/mods in Question**
Combatify

**Expected behavior**
The charge speed to not be slow.

**Video**
Video showing expected behavior (using unmodified weapon) and unexpected behavior (using modified weapon)
https://youtu.be/f370mhrrMh8

**Additional context**
A charged hit, in Combatify/Combat Test Snapshot is when you do not attack with your weapon for a period of time, allowing it to have enhanced reach. This does not work properly on modular items.

**Comment by Smartin-b** [comment]
this issue seems to only be present on forge, combatify seems to divide our attackspeed by 10 for some odd reason
i will look into it further

**Comment by N-10K** [comment]
I forgot to specify I was using forge, thank you for doing that for me. 🙏

**Comment by Smartin-b** [comment]
should be fixed in the next release.
i lost all sanity to terrible forge code.
https://cdn.discordapp.com/attachments/1098169086275489823/1215879991665885264/Truly-Modular-miapi-1.1.13-1.20.1-snapshot-forge.jar?ex=65fe5b7b&is=65ebe67b&hm=ff2e38818f628020dad7a26fe434f0f35e13a421d474a1da7db51de01dd3fb87&
u can try this snapshot jar, the next release should be ready soon

**Comment by Smartin-b** [comment]
should be fixed in 1.1.13
