### ISSUE TITLE
Quark runes do not affect modular item enchantment glint

### ISSUE THREAD

**Issue by AlexTheDolphin0** [Truly-Modular/Modular-Item-API#43]
**Describe the Issue**
A clear and concise description of what the issue is.
Quark's runes change the enchantment glint of items, but this does not work for Truly Modular's modular items.

**The other mod/mods in Question**
The mod/mods the compat is broken or wanted
Quark

**Expected behavior**
The quark runes when applied should change the glint color of modular items the same way as regular items.

**Screenshots**
CRAP I FORGOT the behavior should be pretty easy to replicate though

**Additional context**
Mod versions:
MIAPI v1.1.23-1.20.1 Forge
Quark 4.0-454

**Comment by Smartin-b** [comment]
will be fixed in the next release, here are some snapshots, idk yet when the next release is gonna be
https://cdn.discordapp.com/attachments/1216148507061260409/1247444551077990401/Truly-Modular-miapi-1.1.24-1.20.1-snapshot-forge.jar?ex=66600cc5&is=665ebb45&hm=2c40b9419da447e67fb6478330cd7a44cb87645b8b31c4eb982b1d529eff1617&
https://cdn.discordapp.com/attachments/1216148507061260409/1247444550688051240/Truly-Modular-miapi-1.1.24-1.20.1-snapshot-fabric.jar?ex=66600cc5&is=665ebb45&hm=36800e7ed30d1fb934c925378fb6985abe2e7fd2afd34afd9b07b3ce4926c268&

**Comment by Smartin-b** [comment]
should be fixed now
