### ISSUE TITLE
Request for Compatibility: LHKY's Miracle Road (skill tree), Apotheosis

### ISSUE THREAD

**Issue by kiva9007** [Truly-Modular/Modular-Item-API#44]
If there are any inappropriate terms, I apologize. I'm using translation software and do not speak English.

I would like to request additional support for weapons within the Arsenal for Apotheosis. Currently, most weapons cannot use the Adventure Module in Apotheosis. Adding this support would make it more perfect.

Another request is regarding the possibility of integrating the heavy system from LHKY's Miracle Road (skill tree). This system adds a "heavy" attribute to each piece of armor, creating a burden based on the player's stats. The player's equipped items should not exceed this burden.

I greatly appreciate your creation of these mods. I've been playing Tetra for a long time, but the lack of support for Apotheosis in the bow aspect has always been a concern. Discovering Truly-Modular has rekindled my hope for playing with mods.

If any additional explanation is needed, please let me know and I will provide further details.

**Comment by Smartin-b** [comment]
that the apotheosis adventure module doesnt correctly detect swords is a bug. this will be fixed in the next release.
 LHKY's Miracle Road (skill tree) is not open source/ does not have its source linked so i wont work on compat with it, it shouldnt be too complicated to implement compat though, it would simply be a a synergy in truly modular adding the attribute to its armor. A small datapack could fix that, but im categoricly not gonna work on compat with a mod that is not open source.
