### ISSUE TITLE
Incompatibility with mod cataclysm

### ISSUE THREAD

**Issue by SallyPMB** [Truly-Modular/Modular-Item-API#52]
Ignitium from the mod cataclysm appears to not be compatible with the mod. 

L enders cataclysm

Expected behavior, ingots are usable for Truly modular

Additionally with use of the tool to add compat with the command it spits out an ingot that is clearly different (doesn't stack normally) but still is not a useable material.

**Comment by SallyPMB** [comment]
Ive realised the command portion was user error (still not sure how i messed it up D:)

**Comment by Smartin-b** [comment]
Generative Compatiblity requires a mod to implement a Tool and an Axe from the same Toolmaterial, we need both to have a decent understanding of the Materials stats, Mining speed, Level, Sword Damage, Axe Damage and Axe Speed and Durability are important measures to read to assign stats. Ignitium doesnt have an axe assosiated.
(When we say Toolmaterial we mean that in the code they are implemented as from the same material. some mods might also not do that for various reasons and fail because of that)

The give Command is not meant to make all Instances of an Item into a Material. It gives a material meant for testing ingame and potentially for modpack creators so they might create fancy rare quest rewards. If you want to make all Ignitium Ingots into materials, youll have to use a Datapack, the Material Helper can also create those.

**Comment by SallyPMB** [comment]
Oh that makes a lot of sense thank you!
