### ISSUE TITLE
Netherrocks, Aquaculture 2 & Only silver Effect and texture issue

### ISSUE THREAD

**Issue by idk33333333** [Truly-Modular/Modular-Item-API#54]
**Describe the Issue**
Hello, the swords from "netherrocks" and "aquaculture 2" lose their effects (like the fyrite sword doesn't lit mobs on hit and right click doesn't have a flint and steel effect anymore) and their textures get broken too when modified
Additionally, a bit more niche but "Zot's only silver's" textures also breaks, probably tied to the fact that it uses old style minecraft textures; idk if the textures can be fixed reasonably, but it would be cool to at least keep the effects of the former 2 mods

**The other mod/mods in Question**
https://www.curseforge.com/minecraft/mc-mods/netherrocks
https://www.curseforge.com/minecraft/mc-mods/aquaculture
https://www.curseforge.com/minecraft/mc-mods/zots-only-silver

**Expected behavior**
When you modify a sword that gives an effect like putting the mobs you hit on fire, it should keep this effect post modification, and if it's possible should keep its texture

**Screenshots**
![image](https://github.com/user-attachments/assets/03cc8398-3286-4003-afed-6434936de2d3)
![image](https://github.com/user-attachments/assets/23475ce1-acd5-4ec5-abb0-00a734bbce50)
you can see how the texture warps when i make it into a longsword
![image](https://github.com/user-attachments/assets/744c5c64-b7e9-4e57-ab98-84b2010ff7d1)

**Additional context**
The exact same things happens to the armors of those mods, but i don't think i need to bore you with another long post just to tell you that
Also i wanted to say, this mod is freaking amazing, i don't know how it's not insanely popular, keep up the good work

**Comment by Smartin-b** [comment]
Automaticly detecting on hit effects or right click abilities of weapons is sadly not possible, since there is no dedicated way of implementing them, so any on hit effect would require manual handmade compatiblity.
We wont be working on manual compatiblity oursefls for the forseeable future, as doing a good job there requires decent knowledge of whatever mod you are trying to integrate, but we are working on more tools and documentation + working with some 3rd parties on some addons for dedicated compat for some mods.

When it comes to the textures, we scan the color makeup of the material ingredient, and use that to color the swords on our own pre-made grey-scale textures. This approach obviously has some shortcomings, but most of the time it does a very decent job. You can check https://truly-modular.github.io/Material-Helper/ and make your own color palette and compat materials.
Dynamicly trying to disect modded textures doesnt sound like a sensible solution, since many modded swords are textured very fancy, automatic dection for that pixel belongs to blade, guard,handle, pommel is sadly imposible.
Doing this per hand is possible, but very tedious, and like mentioned above, manual integration of mods is something we aim to leave to third parties, we ourselfs focus on making the api itself as flexbible and making compat as easy to implement as possible.

So for now, this behaviour is what we classified as intended API behaviour.

**Comment by Smartin-b** [comment]
small addition, i changed the description on the modpages and added https://github.com/Truly-Modular/Modular-Item-API/blob/main/COMPAT.md to more clearly communicate what can be expected to be compatible
