### ISSUE TITLE
No compat with DivineRPG and Useless sword

### ISSUE THREAD

**Issue by idk33333333** [Truly-Modular/Modular-Item-API#55]
**Describe the Issue**
Hello just a heads up; the mods "DivineRPG" and "Useless Sword" are not compatible with this mod, you cannot modify most of the swords and armor, although i get why because this seems like a headache to do but i'm reporting it just in case

**The other mod/mods in Question**
https://www.curseforge.com/minecraft/mc-mods/official-divinerpg
https://www.curseforge.com/minecraft/mc-mods/useless-sword

**Expected behavior**
For the swords and armor in those mods to be customizable and their effects to work correctly

**Screenshots**
Not needed

**Additional context**
Not needed

**Comment by Smartin-b** [comment]
We wont be working on making MC-Creator mods compatible, as their code is generated and painfull to integrate because of that.

For Generative Materials to be generated, a Sword and Axe need to be present, as we need to scan for various stats of the Items, (Damage Attack speed , Mining level  Mining speed, durability, axe dmg and attackspeed) to accuratly give the materials sensible stats, you can visit https://truly-modular.github.io/Material-Helper/ to make materials, but making converters for existing items is a bit more advanced in datapacks.
