### ISSUE TITLE
All item models are invisible.

### ISSUE THREAD

**Issue by Surfluff** [Truly-Modular/Modular-Item-API#8]
**Describe the Issue**
All the modular items are completely invisible however the armor models do render just fine.

**The other mod/mods in Question**
I do not know the specific mods, I have attached my modpack mod list.
[modList.txt](https://github.com/Truly-Modular/Modular-Item-API/files/13219832/modList.txt)

**Expected behavior**
I would expect it to render the item models..

**Screenshots**
![Screenshot 2023-10-31 104340](https://github.com/Truly-Modular/Modular-Item-API/assets/61837182/ba3c9241-8279-4e2c-9675-5869d7656a9b)
![Screenshot 2023-10-31 104422](https://github.com/Truly-Modular/Modular-Item-API/assets/61837182/15d058e1-505c-46d9-9846-2c4a8159e609)
![Screenshot 2023-10-31 104429](https://github.com/Truly-Modular/Modular-Item-API/assets/61837182/bf0b1fcf-9088-4282-9086-fcd020b700f0)

**Additional context**
No additional context.

**Comment by Smartin-b** [comment]
This issue is a bit hard to track since its not persistent. ive tried some things and it worked for me, so if possible can you check if this works for you too @Surfluff https://cdn.discordapp.com/attachments/1098169086275489823/1169244860356755466/Truly-Modular-miapi-1.0.2-1.20.1-fabric.jar?ex=6554b322&is=65423e22&hm=10edbac29931364d83f9a46e549bbd07787cbebfafe93f120dd2465b98d976a7&

**Comment by Surfluff** [comment]
That new jar file fixes my issue perfectly. Whatever you did was definitely the fix.
![Screenshot 2023-11-01 090610](https://github.com/Truly-Modular/Modular-Item-API/assets/61837182/a3905ae6-133f-4520-98a5-68db9ee1e2ae)
